# web port
server.port=8998
# no web
#spring.main.web-environment=false

# log config
logging.config=classpath:logback.xml


### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses=http://127.0.0.1:8080/admin

### xxl-job, access token
xxl.job.accessToken=default_token

### xxl-job executor appname
xxl.job.executor.appname=xxl-job-executor-sample
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
xxl.job.executor.address=
### xxl-job executor server-info
xxl.job.executor.ip=127.0.0.1
xxl.job.executor.port=9997
### xxl-job executor log-path
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
### xxl-job executor log-retention-days
xxl.job.executor.logretentiondays=30

### xxl-job, datasource
spring.datasource.url=jdbc:mysql://192.168.2.230:3306/xxl_job_export?useUnicode=true&characterEncoding=UTF-8&useSSL=false
spring.datasource.username=xxl_job_export
spring.datasource.password=YnzdC2f7hjDW6Shj
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.haiwan.url=jdbc:mysql://192.168.2.230:3306/xxl_job_export?useUnicode=true&characterEncoding=UTF-8&useSSL=false
spring.datasource.haiwan.username=xxl_job_export
spring.datasource.haiwan.password=YnzdC2f7hjDW6Shj
spring.datasource.haiwan.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.wc.url=jdbc:mysql://192.168.2.230:3306/xxl_job_export?useUnicode=true&characterEncoding=UTF-8&useSSL=false
spring.datasource.wc.username=xxl_job_export
spring.datasource.wc.password=YnzdC2f7hjDW6Shj
spring.datasource.wc.driver-class-name=com.mysql.cj.jdbc.Driver

### datasource-pool
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=1000

mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.db-type=mysql
mybatis-plus.global-config.db-config.id-type=auto
mybatis-plus.global-config.db-config.field-strategy=not_empty
mybatis-plus.global-config.db-config.table-underline=true
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.mapper-locations=classpath:/mapper/*.xml

# ????SSH??
ssh.enabled=false 
# SSH??
ssh.host=127.0.0.1 
# SSH??
ssh.port=22 
# SSH???
ssh.username=
# SSH??
ssh.password=
# ???????
ssh.forward.from_host=
# ???????
ssh.forward.from_port=
# ?????????
ssh.forward.to_host=
# ?????????
ssh.forward.to_port=